# Generated by Django 4.2 on 2023-07-31 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='Reports',
        ),
    ]
