# Generated by Django 4.2 on 2023-07-31 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_report_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
