# Generated by Django 4.2 on 2023-07-31 18:52

import App.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_reports_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='reportType',
            field=django_enumfield.db.fields.EnumField(default=1, enum=App.models.ReportType),
        ),
    ]
