# Generated by Django 4.2 on 2023-08-12 18:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_order_time_alter_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.profile')),
            ],
        ),
    ]
