# Generated by Django 4.2 on 2023-08-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_record'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Report',
        ),
    ]
