# Generated by Django 4.2 on 2023-08-18 20:49

import App.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0010_rename_reports_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeleOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('status', django_enumfield.db.fields.EnumField(default=1, enum=App.models.Status)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.teleuser')),
            ],
        ),
    ]
