# Generated by Django 4.2 on 2023-08-19 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_remove_teleuser_user_teleuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleuser',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='teleuser',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
